export const globalFilters = {
  // Keywords to match in job titles
  keywords: [
    'Software Engineer',
    'Software Development Engineer',
    'SDE',
    'Machine Learning',
    'ML Engineer',
    'Data Visualization',
    'Data Engineer',
    'Computer Vision',
    'AI Engineer',
    'Intern',
    'Internship',
    'New Grad',
    'New Graduate',
    'Entry Level',
    'Associate',
    'Full Stack',
    'Backend',
    'Frontend',
    'DevOps',
    'Cloud Engineer',
    'Data Scientist',
    'Research Scientist'
  ],
  
  // Location filters (case-insensitive partial match)
  // Only USA locations - jobs must match one of these
  locations: [
    'United States',
    'USA',
    'US',
    'Remote',
    'US Remote',
    'Remote US',
    'California',
    'CA',
    'Washington',
    'WA',
    'Texas',
    'TX',
    'New York',
    'NY',
    'Massachusetts',
    'MA',
    'Illinois',
    'IL',
    'Arizona',
    'AZ',
    'Colorado',
    'CO',
    'Oregon',
    'OR',
    'North Carolina',
    'NC',
    'Georgia',
    'GA',
    'Florida',
    'FL',
    'Pennsylvania',
    'PA',
    'Michigan',
    'MI',
    'Ohio',
    'OH',
    'Virginia',
    'VA',
    'Tennessee',
    'TN',
    'Indiana',
    'IN',
    'Missouri',
    'MO',
    'Maryland',
    'MD',
    'Wisconsin',
    'WI',
    'Minnesota',
    'MN',
    'Louisiana',
    'LA',
    'Alabama',
    'AL',
    'Kentucky',
    'KY',
    'Connecticut',
    'CT',
    'Iowa',
    'IA',
    'Utah',
    'UT',
    'Nevada',
    'NV',
    'New Jersey',
    'NJ',
    'Kansas',
    'KS',
    'Oklahoma',
    'OK',
    'Nebraska',
    'NE',
    'New Mexico',
    'NM',
    'West Virginia',
    'WV',
    'Hawaii',
    'HI',
    'New Hampshire',
    'NH',
    'Maine',
    'ME',
    'Rhode Island',
    'RI',
    'Montana',
    'MT',
    'Delaware',
    'DE',
    'South Dakota',
    'SD',
    'North Dakota',
    'ND',
    'Alaska',
    'AK',
    'Vermont',
    'VT',
    'Wyoming',
    'WY',
    'Idaho',
    'ID'
  ],
  
  // Locations to exclude (non-USA locations)
  excludeLocations: [
    'Canada',
    'CAN',
    'Toronto',
    'Vancouver',
    'Montreal',
    'Mexico',
    'MEX',
    'London',
    'UK',
    'United Kingdom',
    'England',
    'Ireland',
    'Dublin',
    'Germany',
    'Berlin',
    'Munich',
    'France',
    'Paris',
    'Netherlands',
    'Amsterdam',
    'Switzerland',
    'Zurich',
    'India',
    'Bangalore',
    'Hyderabad',
    'Pune',
    'Mumbai',
    'Delhi',
    'China',
    'Beijing',
    'Shanghai',
    'Singapore',
    'Australia',
    'Sydney',
    'Melbourne',
    'Japan',
    'Tokyo',
    'South Korea',
    'Seoul',
    'Brazil',
    'São Paulo',
    'Argentina',
    'Buenos Aires',
    'Israel',
    'Tel Aviv',
    'Poland',
    'Warsaw',
    'Spain',
    'Madrid',
    'Barcelona',
    'Italy',
    'Milan',
    'Rome',
    'Sweden',
    'Stockholm',
    'Denmark',
    'Copenhagen',
    'Norway',
    'Oslo',
    'Finland',
    'Helsinki',
    'Belgium',
    'Brussels',
    'Austria',
    'Vienna',
    'Portugal',
    'Lisbon',
    'Czech Republic',
    'Prague',
    'Hungary',
    'Budapest',
    'Greece',
    'Athens',
    'Romania',
    'Bucharest',
    'Turkey',
    'Istanbul',
    'Russia',
    'Moscow',
    'South Africa',
    'Cape Town',
    'Johannesburg',
    'Egypt',
    'Cairo',
    'UAE',
    'Dubai',
    'Abu Dhabi',
    'Saudi Arabia',
    'Riyadh',
    'Qatar',
    'Doha',
    'Kuwait',
    'Kuwait City',
    'Bahrain',
    'Manama',
    'Oman',
    'Muscat',
    'Jordan',
    'Amman',
    'Lebanon',
    'Beirut',
    'Iraq',
    'Baghdad',
    'Iran',
    'Tehran',
    'Pakistan',
    'Karachi',
    'Lahore',
    'Islamabad',
    'Bangladesh',
    'Dhaka',
    'Sri Lanka',
    'Colombo',
    'Nepal',
    'Kathmandu',
    'Bhutan',
    'Thimphu',
    'Myanmar',
    'Yangon',
    'Thailand',
    'Bangkok',
    'Vietnam',
    'Ho Chi Minh',
    'Hanoi',
    'Indonesia',
    'Jakarta',
    'Malaysia',
    'Kuala Lumpur',
    'Philippines',
    'Manila',
    'Taiwan',
    'Taipei',
    'Hong Kong',
    'New Zealand',
    'Auckland',
    'Wellington'
  ],
  
  // Visa-friendly companies (most companies in the list are visa-friendly)
  // This is mainly for companies that explicitly don't sponsor
  visaFriendlyCompanies: [
    // All companies are visa-friendly by default unless marked otherwise
    // Companies marked visaFriendly: false in companies.js will be excluded
  ],
  
  // Require visa-friendly companies only
  requireVisaFriendly: true,
  
  // Maximum age of job posting (in days) - only show recent postings
  maxJobAgeDays: 14, // Only jobs posted in last 2 weeks
  
  // Minimum priority level to check (1 = highest, 5 = lowest)
  // Set to 1 to only check high-priority companies, or null to check all
  minPriority: null,
  
  // Limit number of companies to check (for testing - set to null for all)
  maxCompanies: null,
  
  // Experience level filter - maximum years of experience required
  maxExperienceYears: 3, // Only show jobs requiring 0-3 years of experience
  
  // Experience level keywords to exclude (jobs requiring more experience)
  excludeExperienceKeywords: [
    'senior',
    'sr.',
    'sr ',
    'lead',
    'principal',
    'staff',
    'architect',
    'manager',
    'director',
    '4+ years',
    '5+ years',
    '6+ years',
    '7+ years',
    '8+ years',
    '9+ years',
    '10+ years',
    '4 years',
    '5 years',
    '6 years',
    '7 years',
    '8 years',
    '9 years',
    '10 years',
    'four years',
    'five years',
    'six years',
    'seven years',
    'eight years',
    'nine years',
    'ten years'
  ],
  
  // Always include these roles regardless of experience keywords
  alwaysIncludeKeywords: [
    'intern',
    'internship',
    'new grad',
    'new graduate',
    'entry level',
    'associate',
    'junior'
  ]
};

